package main.controller.course;

import main.business_logic.DefaultLogic;
import main.controller.MainController;
import main.database.course.CourseDatabaseLogic;
import main.ui.course.COURSE;
import main.models.CourseModel;
import java.util.Date;

public class CourseController {

    public static void courseMenu() {
        try
        {
            String input = DefaultLogic.handleInput();
            int inputConvertedToInteger = Integer.parseInt(input);
            switch(inputConvertedToInteger) {
                case 1: // Create Course
                    // Print create course menu
                    System.out.println(COURSE.CREATE_COURSE);
                    // Initialize create course input
                    handleCreateCourseInput();
                    break;
                case 2: // Assign Teacher
                    break;
                case 3: // Assign Range
                    break;
                case 4: // Assign Class
                    break;
                case 5: // Go back to main menu
                    MainController.initializeMainMenu();
                    break;
                default:
                    // code block
            }
        }
        catch (Exception e)
        {
            System.out.println(e);
        }
    }

    public static Date validateDateInput(String date) {
        Date parsedDate = new Date(date);
        if (parsedDate != null) {
            return parsedDate;
        } else {
            return null;
        }
    }

    public static void handleCreateCourseInput() {
        CourseModel courseModel = new CourseModel();
        //TODO: ENSURE THE ID is autogenerated
//        System.out.print("Enter Course Id:");
//        courseModel.setCourse_id(Integer.parseInt(DefaultLogic.handleInput()));
        System.out.print("Enter Course Name:");
        courseModel.setName(DefaultLogic.handleInput());
        System.out.print("Enter Course Description:");
        courseModel.setDescription(DefaultLogic.handleInput());
        System.out.print("Enter Course Type:");
        courseModel.setType(DefaultLogic.handleInput());
        // Print Enter Course Date
        System.out.print("Enter Course Date(yyyy-MM-dd):");
        // Get user input
        String dateInput = DefaultLogic.handleInput();
        // Send input to validator
        Date dateFormat = null;
        while (dateFormat == null) {
            try {
                dateFormat = validateDateInput(dateInput);
            }catch (Exception e) {
                System.out.print("Try again, please use format(yyyy-MM-dd):");
                dateInput = DefaultLogic.handleInput();
                dateFormat = validateDateInput(dateInput);
            }
        }
        courseModel.setDate(dateFormat);
        System.out.print("Enter Course Cost:");
        courseModel.setCost(Float.parseFloat(DefaultLogic.handleInput()));
        System.out.print("Enter Range Number:");
        courseModel.setRange_number(Integer.parseInt(DefaultLogic.handleInput()));
        System.out.print("Enter True or False if Range is AM:");
        courseModel.setRange_am(Boolean.parseBoolean(DefaultLogic.handleInput()));
        System.out.print("Enter True or False if Range is PM:");
        courseModel.setRange_pm(Boolean.parseBoolean(DefaultLogic.handleInput()));
        CourseDatabaseLogic.submitCreateCourseDataToDatabase(courseModel);

        MainController.initializeMainMenu();

    }
}
