package main.controller.course;

import main.business_logic.DefaultLogic;
import main.database.course.CourseDatabaseLogic;
import main.ui.course.COURSE;
import main.models.CourseModel;

import java.text.SimpleDateFormat;

public class CourseController {

    public static void courseMenu() {
        try
        {
            String input = DefaultLogic.handleInput();
            int inputConvertedToInteger = Integer.parseInt(input);
            switch(inputConvertedToInteger) {
                case 1: // Create Course
                    // Print create course menu
                    System.out.println(COURSE.CREATE_COURSE);
                    // Initialize create course input
                    handleCreateCourseInput();
                    break;
                case 2: // Assign Teacher
                    break;
                case 3: // Assign Range
                    break;
                case 4: // Assign Class
                    break;
                default:
                    // code block
            }
        }
        catch (Exception e)
        {
            System.out.println(e);
        }
    }

    public static void handleCreateCourseInput() {
        CourseModel courseModel = new CourseModel();
        //TODO: ENSURE THE ID is autogenerated
        System.out.print("Enter Course Id:");
        courseModel.setCourse_id(Integer.parseInt(DefaultLogic.handleInput()));
        System.out.print("Enter Course Name:");
        courseModel.setName(DefaultLogic.handleInput());
        System.out.print("Enter Course Description:");
        courseModel.setDescription(DefaultLogic.handleInput());
        System.out.print("Enter Course Type:");
        courseModel.setType(DefaultLogic.handleInput());
        System.out.print("Enter Course Date(yyyy-MM-dd):");
        courseModel.setDate(new SimpleDateFormat(DefaultLogic.handleInput()));
        System.out.print("Enter Course Cost:");
        courseModel.setCost(Float.parseFloat(DefaultLogic.handleInput()));

        CourseDatabaseLogic.submitCreateCourseDataToDatabase(courseModel);


    }
}
